baseurl = "http://petar.io/"
languageCode = "en-us"
title = "Petar Slovic - JS Warrior"
googleAnalytics = "UA-69788212-1"
disqusShortname = "petarslovic"

[params]
  name = "Petar Slović 123321"
  aboutAuthor = "Architecting complex, dynamic and highly interactive web applications through JavaScript and lots of coffee. Specializing in Angular JS and enthusiasm."
  description = "JS Developer and Team Leader. Passionate about turning ideas into products and spreading the knowledge. JavaScript all the things!"
  title = "JavaScript Warrior"
  tagline = "petar@petar.io"
  enableRSS = true
  copyright = "**Petar Slovic** - All code under [MIT Licence](http://opensource.org/licenses/MIT)"

[social]
  twitter  = "https://twitter.com/PetarSlovic"
  facebook = "https://www.facebook.com/petar.slovic"
  linkedin = "https://rs.linkedin.com/in/petar-slović-78275067"
  github = "https://github.com/petarslovic"
  skype = "skype:petar.slovic?chat"
  mail = "mailto:petar@petar.io"
  cv = "https://rs.linkedin.com/in/petar-slović-78275067"
  rss = ""
