baseurl = "http://petarslovic.com/"
languageCode = "en-us"
title = "Petar Slovic - JS Warrior"
googleAnalytics = ""
disqusShortname = "petarslovic"

[params]
  name = "Petar Slović"
  aboutAuthor = "Architecting complex, dynamic and highly interactive web applications through JavaScript and lots of coffee. Specializing in Angular JS and enthusiasm."
  description = "Petar Slovic Desc"
  title = "JavaScript Warrior"
  tagline = "petar@petarslovic.com"
  enableRSS = true
  copyright = "**Petar Slovic** - All code under [MIT Licence](http://opensource.org/licenses/MIT)"

[social]
  twitter  = "https://twitter.com/PetarSlovic"
  facebook = "https://www.facebook.com/petar.slovic"
  linkedin = "https://rs.linkedin.com/in/petar-slović-78275067"
  github = "https://github.com/petarslovic"
  skype = "skype:petar.slovic?chat"
  mail = "mailto:petar@petarslovic.com"
  cv = "#"
  rss = ""